app/models.py
import os
from urllib.request import urlretrieve
from time import strftime
from datetime import datetime

from app import db, login

from flask import current_app, flash
from werkzeug.security import check_password_hash, generate_password_hash
from flask_login import UserMixin


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    password_hash = db.Column(db.String(128))

    def __repr__(self):
        return '<User {}>'.format(self.username)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)


@login.user_loader
def load_user(id):
    return User.query.get(int(id))


class Photo(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    filename = db.Column(db.String(64))
    file_path = db.Column(db.String(128), unique=True)
    created = db.Column(db.DateTime, default=datetime.now())

    def save_photo(self):
        img_url = current_app.config['IP_WEBCAM_PHOTO_URL']

        urlretrieve(img_url, filename=self.file_path)

    def delete_photo(self):
        os.remove(self.file_path)

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_bootstrap import Bootstrap
from flask_login import LoginManager

from config import Config

db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()
login.login_view = 'auth.login'
login.login_message = 'Please log in to access this page.'
login.login_message_category = 'info'
bootstrap = Bootstrap()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    migrate.init_app(app, db)
    login.init_app(app)
    bootstrap.init_app(app)

    from app.errors import bp as errors_bp
    app.register_blueprint(errors_bp)

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp, url_prefix='/auth')

    from app.webcam import bp as webcam_bp
    app.register_blueprint(webcam_bp)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    return app

from app import models

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template

from app.main import bp


@bp.route('/')
def index():
    return render_template('index.html')

app/routes.py
from app import app, db

from flask import render_template, redirect, url_for, flash, request
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.urls import url_parse

from app.forms import LoginForm, RegistrationForm
from app.models import User

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/photo')
@login_required
def photo():
    img_url = app.config['IP_WEBCAM_PHOTO_URL']
    return render_template('photo.html', img_url=img_url)


@app.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            flash('Invalid username or password')
            return redirect(url_for('login'))
        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('index')
        return redirect(next_page)
    return render_template('login.html', title='Sign In', form=form)

@app.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Congratulations, you are now a registered user!')
        return redirect(url_for('login'))
    return render_template('register.html', title='Register', form=form)


@app.route('/logout')
def logout():
        logout_user()
        return redirect(url_for('index'))

app/webcam/__init__.py
from flask import Blueprint

bp = Blueprint('webcam', __name__)

from app.webcam import routes

app/webcam/routes.py
from flask import render_template, current_app, redirect, url_for, flash
from flask_login import login_required
import os
from datetime import datetime

from urllib.request import urlopen, urlretrieve
from urllib.error import URLError, HTTPError

from app import db
from app.webcam import bp
from app.models import Photo


@bp.route('/photo')
@login_required
def photo():
    img_url = current_app.config['IP_WEBCAM_PHOTO_URL']
    try:
        response = urlopen(img_url, timeout=3).getcode()
    except URLError as e:
        flash('Error: {0}'.format(str(e.errno)), 'danger')
        return redirect(url_for('main.index'))
    else:
        print("All ok")

    return render_template('webcam/photo.html', img_url=img_url)


@bp.route('/save_photo/')
@login_required
def save_photo():
    filename = datetime.now().strftime("%Y%m%d-%H.%M.%S") + ".jpg"
    file_url = os.path.join(current_app.config['GALLERY_ROOT_DIR'], filename)
    try:
        p = Photo(filename=filename, file_path=file_url)
        db.session.add(p)
        db.session.commit()
        p.save_photo()
        flash('Image was saved as: ' + filename, 'success')
    except URLError as e:
        flash('Error: {0}'.format(str(e.errno)), 'warning')
        return redirect(url_for('main.index'))
    return redirect(url_for('webcam.photo'))


@bp.route('/delete_photo/<filename>')
@login_required
def delete_photo(filename):
    p = Photo.query.filter_by(filename=filename).first()
    if p is not None:
        db.session.delete(p)
        db.session.commit()
        p.delete_photo()
        flash('{} deleted.'.format(filename), 'success')
    else:
        flash('Could not delete photo.', 'warning')
    return redirect(url_for('webcam.show_gallery'))


@bp.route('/show_gallery/')
@login_required
def show_gallery():
    photos = Photo.query.all()
    return render_template('webcam/gallery.html', photos=photos)

app/templates/base.html
<!doctype html>

<head>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bulma.css') }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.png') }}" type="image/x-icon">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <script src="{{ url_for('static', filename='js/jquery-3.3.1.min.js')}}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/main.js')}}"></script>

    <title>{% if title %}
        {{ title }}
        {% else %}
        Homecam
        {% endif %}
    </title>
</head>


{% block navbar %}
<nav class="navbar has-shadow has-background-primary" role="navigation" aria-label="main navigation">
    <div class="container">
        <div class="navbar-brand">
            <a href="#" class="navbar-item">
                <strong>HomeCam</strong>
            </a>
            <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
               data-target="navbarBasicExample">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>
        <div id="navbarBasicExample" class="navbar-menu">
            <div class="navbar-start">
                <a href="{{ url_for('webcam.photo') }}" class="navbar-item has-text-black-ter">
                    <span class="icon has-text-info"><i class="fas fa-camera"></i></span>
                    <span>Snapshot</span>
                </a>
                <a href="{{ url_for('webcam.show_gallery') }}" class="navbar-item has-text-black-ter">
                    <span class="icon has-text-danger"><i class="fas fa-images"></i></span>
                    <span>Gallery</span>
                </a>

            </div>
        </div>
        <div class="navbar-end">
            <div class="navbar-item">
                <div class="buttons">

                    {% if current_user.is_anonymous %}
                    <a href="{{ url_for('auth.login') }}" class="button is-light">
                        <strong>Login</strong>
                    </a>
                    {% else %}
                    <a href="{{ url_for('auth.logout') }}" class="button is-light">
                        Logout
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</nav>
{% endblock %}

{% block content %}
<div class="section">
    <div class="container">
        {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="columns">
            <div class="column is-half">
                <article class="message is-{{ category }}">
                    <div class="message-header">
                        <p>{{ category|capitalize }}</p>
                    </div>
                    <div class="message-body">
                        {{ message }}
                    </div>
                </article>
            </div>
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        {% block page_content %} {% endblock %}
    </div>
</div>

{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

Hello

app/templates/login.html
{% extends "base.html" %}


{% block page_content %}
<h1>Sign in</h1>
<form action="" method="post" novalidate>
    {{ form.hidden_tag() }}
    <p>
        {{ form.username.label }}<br>
        {{ form.username(size=32) }}
    </p>
    <p>
        {{ form.password.label }}<br>
        {{ form.password(size=32) }}
    </p>
    <p>
        {{ form.remember_me() }} {{ form.remember_me.label }}
    </p>
    <p>
        {{ form.submit() }}
    </p>
</form>
{% endblock %}

app/templates/webcam/gallery.html
{% extends "base.html" %}

{% block page_content %}
<div class="container">
    <h1 class="title has-text-grey">Thumbnail Gallery</h1>
    <div class="columns is-multiline">

    {% if photos|length > 0 %}
    {% for photo in photos | sort(attribute='filename', reverse=True) %}
        <div class="column is-4-desktop is-6-tablet">
            <div class="card">
                <div class="card-image">
                    <figure class="image">
                        <img onclick="openCardModal({{ loop.index }})"
                             src="{{ url_for('static', filename='photos/' + photo.filename) }}" alt="">
                    </figure>
                </div>
                <footer class="card-footer">
                    <a class="card-footer-item" role="button" href="#">More info</a>
                    <a href="{{ url_for('webcam.delete_photo', filename=photo.filename) }}"
                       class="card-footer-item">Delete</a>
                </footer>
            </div>
        </div>
        <div id="modal-{{ loop.index }}" class="modal">
            <div class="modal-background"></div>
            <div class="modal-content is-huge is-image">
                <!-- content -->
                <img src="{{ url_for('static', filename='photos/' + photo.filename) }}" alt="image">
                <!-- end content -->
            </div>
            <button onclick="closeCardModal({{ loop.index }})"
                    class="modal-close is-large" aria-label="close"></button>
        </div>
    {% endfor %}
    {% else %}
        <div class="alert alert-info" role="alert">
            <strong>Heads up!</strong>
            There are no photos here.
        </div>
    {% endif %}
</div>
</div>
{% endblock %}

app/templates/webcam/photo.html
{% extends "base.html" %}

{% block page_content %}

<div class="container">

    <form action="{{ url_for('webcam.save_photo')}}">
        <button type="submit" class="button is-primary">Save image</button>
    </form>

    <div class="columns">
        <div class="column is-half">
            <img src="{{ img_url }}" width="100%" alt="">
        </div>
    </div>


</div>
{% endblock %}